# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
target 'Chowtime' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Chowtime
  pod 'UberRides'

  target 'Chowtime-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChowtimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Chowtime-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Chowtime-tvOS

  target 'Chowtime-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
